(() => {
  'use strict';
  const MAX = 200, THUMB = 520, $ = id => document.getElementById(id);
  const e = {
    uploadScreen:$('uploadScreen'),gameScreen:$('gameScreen'),winnerScreen:$('winnerScreen'),rankingScreen:$('rankingScreen'),
    input:$('photoInput'),uploadLabel:$('uploadLabel'),uploadHint:$('uploadHint'),uploadProgress:$('uploadProgress'),uploadProgressText:$('uploadProgressText'),uploadProgressBar:$('uploadProgressBar'),selectedArea:$('selectedArea'),selectedCount:$('selectedCount'),thumbStrip:$('thumbStrip'),startButton:$('startButton'),clearButton:$('clearButton'),
    roundLabel:$('roundLabel'),matchLabel:$('matchLabel'),gameProgressBar:$('gameProgressBar'),leftCandidate:$('leftCandidate'),rightCandidate:$('rightCandidate'),leftImage:$('leftImage'),rightImage:$('rightImage'),undoButton:$('undoButton'),gameHomeButton:$('gameHomeButton'),
    winnerBackdrop:$('winnerBackdrop'),confetti:$('confetti'),winnerHomeButton:$('winnerHomeButton'),shareWinnerButton:$('shareWinnerButton'),openWinnerButton:$('openWinnerButton'),rankingButton:$('rankingButton'),rankingBackButton:$('rankingBackButton'),rankingHomeButton:$('rankingHomeButton'),podium:$('podium'),rankingGrid:$('rankingGrid'),rematchButton:$('rematchButton'),newSetLabel:$('newSetLabel'),
    lightbox:$('lightbox'),lightboxClose:$('lightboxClose'),lightboxImage:$('lightboxImage'),lightboxRank:$('lightboxRank'),lightboxName:$('lightboxName'),lightboxShare:$('lightboxShare'),lightboxPrev:$('lightboxPrev'),lightboxNext:$('lightboxNext'),downloadOriginal:$('downloadOriginal'),toast:$('toast')
  };
  const s={photos:[],keys:new Set(),replace:false,pool:[],initial:0,players:[],matches:[],winners:[],index:0,current:null,label:'',locked:false,history:[],elim:0,champion:null,ranking:[],lightbox:0,timer:null};
  const key=f=>`${f.name}|${f.size}|${f.lastModified}`;
  const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const power=n=>n>0&&(n&(n-1))===0;
  const lower=n=>2**Math.floor(Math.log2(n));
  const imageFile=f=>f.type.startsWith('image/')||/\.(jpe?g|png|webp|gif|bmp|avif|heic|heif)$/i.test(f.name||'');
  function screen(name){const map={upload:e.uploadScreen,game:e.gameScreen,winner:e.winnerScreen,ranking:e.rankingScreen};Object.values(map).forEach(x=>x.classList.remove('active'));map[name].classList.add('active');scrollTo({top:0,behavior:'instant'})}
  function toast(m){clearTimeout(s.timer);e.toast.textContent=m;e.toast.classList.add('show');s.timer=setTimeout(()=>e.toast.classList.remove('show'),2200)}
  function busy(on,done=0,total=0){e.uploadProgress.classList.toggle('hidden',!on);e.uploadLabel.classList.toggle('hidden',on||s.photos.length>0);e.selectedArea.classList.toggle('hidden',on||!s.photos.length);if(on){e.uploadProgressText.textContent=`사진 준비 중 ${done} / ${total}`;e.uploadProgressBar.style.width=`${total?done/total*100:0}%`}}
  async function decode(file,url){if('createImageBitmap'in window){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch{}}return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=url})}
  async function prepare(file){const original=URL.createObjectURL(file);try{const src=await decode(file,original),w=src.width||src.naturalWidth,h=src.height||src.naturalHeight;if(!w||!h)throw Error();const scale=Math.min(1,THUMB/Math.max(w,h)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));const x=c.getContext('2d',{alpha:false});x.fillStyle='#f7eef1';x.fillRect(0,0,c.width,c.height);x.drawImage(src,0,0,c.width,c.height);src.close?.();const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.78));return{id:uid(),file,name:file.name||'photo',original,thumb:blob?URL.createObjectURL(blob):original,owned:!!blob,seed:Math.random(),stats:null}}catch(err){URL.revokeObjectURL(original);throw err}}
  async function addFiles(list){let files=[...(list||[])].filter(imageFile);if(!files.length){toast('읽을 수 있는 이미지가 없습니다.');e.input.value='';return}if(s.replace){clear(false);s.replace=false;screen('upload')}files=files.filter(f=>!s.keys.has(key(f))).slice(0,MAX-s.photos.length);if(!files.length){toast(s.photos.length>=MAX?`최대 ${MAX}장까지 가능합니다.`:'이미 추가된 사진입니다.');e.input.value='';return}busy(true,0,files.length);let done=0,failed=0;for(let i=0;i<files.length;i+=4){const batch=files.slice(i,i+4),results=await Promise.allSettled(batch.map(prepare));results.forEach((r,j)=>{if(r.status==='fulfilled'){s.photos.push(r.value);s.keys.add(key(batch[j]))}else failed++;done++;busy(true,done,files.length)});await new Promise(r=>setTimeout(r,0))}e.input.value='';renderSelected();busy(false);toast(failed?`${failed}장은 열 수 없었습니다.`:`${done}장 추가 완료`)}
  function dispose(p){URL.revokeObjectURL(p.original);if(p.owned&&p.thumb!==p.original)URL.revokeObjectURL(p.thumb)}
  function remove(id){const p=s.photos.find(x=>x.id===id);if(!p)return;dispose(p);s.keys.delete(key(p.file));s.photos=s.photos.filter(x=>x.id!==id);renderSelected()}
  function clear(notice=true){s.photos.forEach(dispose);s.photos=[];s.keys.clear();s.pool=[];s.ranking=[];s.champion=null;renderSelected();if(notice)toast('사진을 모두 지웠습니다.')}
  function renderSelected(){const n=s.photos.length;e.uploadLabel.classList.toggle('hidden',n>0);e.selectedArea.classList.toggle('hidden',!n);e.selectedCount.textContent=`${n}장`;e.startButton.disabled=n<2;e.uploadHint.textContent=n?`${n}장 선택됨`:'여러 장을 한 번에 골라주세요';e.thumbStrip.replaceChildren();s.photos.forEach((p,i)=>{const card=document.createElement('div');card.className='thumb';const img=new Image;img.src=p.thumb;img.alt=p.name;img.loading='lazy';const no=document.createElement('span');no.className='thumb-index';no.textContent=i+1;const del=document.createElement('button');del.className='thumb-remove';del.type='button';del.textContent='×';del.ariaLabel=`${p.name} 삭제`;del.onclick=()=>remove(p.id);card.append(img,no,del);e.thumbStrip.append(card)})}
  function reset(pool){pool.forEach(p=>p.stats={wins:0,losses:0,matches:0,byes:0,elo:1000,round:null,at:null,lostTo:null,opponents:[],champion:false})}
  function opening(players){const a=shuffle(players);if(power(a.length))return shuffle(Array.from({length:a.length/2},(_,i)=>[a[i*2],a[i*2+1]]));const target=lower(a.length),pre=a.length-target,byes=target-pre,out=[];let c=0;for(let i=0;i<pre;i++){out.push([a[c],a[c+1]]);c+=2}for(let i=0;i<byes;i++)out.push([a[c++],null]);return shuffle(out)}
  function pairs(players){const a=shuffle(players),out=[];for(let i=0;i<a.length;i+=2)out.push([a[i],a[i+1]||null]);return out}
  function roundName(n,first){if(first&&!power(s.initial))return `${s.initial}장 · 예선`;if(n===2)return'FINAL';if(n===4)return'SEMI FINAL';if(n===8)return'TOP 8';if(n===16)return'TOP 16';return`${n}강`}
  function start(pool=s.photos){if(pool.length<2)return;s.pool=[...pool];s.initial=pool.length;s.elim=0;s.history=[];s.ranking=[];s.champion=null;reset(s.pool);screen('game');begin([...s.pool],true)}
  function begin(players,first=false){s.players=[...players];s.matches=first?opening(players):pairs(players);s.winners=[];s.index=0;s.current=null;s.label=roundName(players.length,first);e.roundLabel.textContent=s.label;next()}
  const playable=()=>s.matches.filter(m=>m[1]);
  function next(){while(s.index<s.matches.length){const m=s.matches[s.index];if(!m[1]){m[0].stats.byes++;s.winners.push(m[0]);s.index++;continue}s.current=m;renderMatch();return}if(s.winners.length===1)finish(s.winners[0]);else begin(s.winners,false)}
  function renderMatch(){const[l,r]=s.current;e.leftImage.src=l.original;e.leftImage.alt=l.name;e.rightImage.src=r.original;e.rightImage.alt=r.name;e.leftCandidate.classList.remove('chosen','rejected');e.rightCandidate.classList.remove('chosen','rejected');s.locked=false;e.undoButton.disabled=!s.history.length;const p=playable(),i=s.matches.slice(0,s.index).filter(m=>m[1]).length;e.matchLabel.textContent=`${i+1} / ${p.length}`;e.gameProgressBar.style.width=`${p.length?i/p.length*100:100}%`}
  function snap(){return{players:[...s.players],matches:s.matches.map(x=>[...x]),winners:[...s.winners],index:s.index,current:s.current?[...s.current]:null,label:s.label,elim:s.elim,stats:s.pool.map(p=>[p.id,{...p.stats,opponents:[...p.stats.opponents]}])}}
  function restore(x){s.players=x.players;s.matches=x.matches;s.winners=x.winners;s.index=x.index;s.current=x.current;s.label=x.label;s.elim=x.elim;const m=new Map(x.stats);s.pool.forEach(p=>p.stats={...m.get(p.id),opponents:[...m.get(p.id).opponents]});e.roundLabel.textContent=s.label;screen('game');renderMatch()}
  const expected=(a,b)=>1/(1+10**((b-a)/400));
  function stats(win,lose){const ew=expected(win.stats.elo,lose.stats.elo);win.stats.elo+=36*(1-ew);lose.stats.elo+=36*(0-(1-ew));win.stats.wins++;win.stats.matches++;lose.stats.losses++;lose.stats.matches++;win.stats.opponents.push(lose.id);lose.stats.opponents.push(win.id);lose.stats.round=s.players.length;lose.stats.at=s.elim++;lose.stats.lostTo=win.id}
  function choose(side){if(s.locked||!s.current)return;s.locked=true;s.history.push(snap());if(s.history.length>24)s.history.shift();const win=s.current[side==='left'?0:1],lose=s.current[side==='left'?1:0],yes=side==='left'?e.leftCandidate:e.rightCandidate,no=side==='left'?e.rightCandidate:e.leftCandidate;yes.classList.add('chosen');no.classList.add('rejected');stats(win,lose);s.winners.push(win);const p=playable(),done=s.matches.slice(0,s.index+1).filter(m=>m[1]).length;e.gameProgressBar.style.width=`${done/p.length*100}%`;navigator.vibrate?.(25);setTimeout(()=>{s.index++;next()},390)}
  function undo(){if(s.locked||!s.history.length)return;restore(s.history.pop());toast('이전 선택으로 돌아갔습니다.')}
  function rank(champion){champion.stats.champion=true;const by=new Map(s.pool.map(p=>[p.id,p])),strength=p=>p.stats.opponents.reduce((a,id)=>a+(by.get(id)?.stats.wins||0),0);return[...s.pool].sort((a,b)=>{if(a.id===champion.id)return-1;if(b.id===champion.id)return 1;const ar=a.stats.round??Infinity,br=b.stats.round??Infinity;if(ar!==br)return ar-br;if(a.stats.wins!==b.stats.wins)return b.stats.wins-a.stats.wins;const st=strength(b)-strength(a);if(st)return st;const elo=b.stats.elo-a.stats.elo;if(Math.abs(elo)>.001)return elo;return(b.stats.at??-1)-(a.stats.at??-1)||a.seed-b.seed})}
  function confetti(){e.confetti.replaceChildren();const colors=['#ff7198','#78b9ff','#ffdc6a','#9de0c4','#fff'];for(let i=0;i<42;i++){const x=document.createElement('i');x.style.left=`${Math.random()*100}%`;x.style.setProperty('--c',colors[i%colors.length]);x.style.setProperty('--d',`${3.5+Math.random()*3.2}s`);x.style.setProperty('--delay',`${-Math.random()*5}s`);x.style.setProperty('--r',`${Math.random()*180}deg`);e.confetti.append(x)}}
  function finish(champion){s.champion=champion;s.ranking=rank(champion);e.winnerBackdrop.src=champion.original;e.winnerBackdrop.alt=champion.name;confetti();renderRanking();screen('winner');navigator.vibrate?.([55,45,100])}
  function podium(p,n,cls=''){const b=document.createElement('button');b.type='button';b.className=`podium-card ${cls}`.trim();const img=new Image;img.src=p.thumb;img.alt=`${n}위 ${p.name}`;const badge=document.createElement('span');badge.className='podium-rank';badge.textContent=n===1?'♛':n;b.append(img,badge);b.onclick=()=>lightbox(n-1);return b}
  function renderRanking(){e.podium.replaceChildren();e.rankingGrid.replaceChildren();const top=s.ranking.slice(0,3);if(top.length===1)e.podium.append(podium(top[0],1,'first'));else{if(top[1])e.podium.append(podium(top[1],2));e.podium.append(podium(top[0],1,'first'));if(top[2])e.podium.append(podium(top[2],3))}s.ranking.slice(3).forEach((p,i)=>{const n=i+4,b=document.createElement('button');b.type='button';b.className='rank-card';const img=new Image;img.src=p.thumb;img.alt=`${n}위 ${p.name}`;img.loading='lazy';const badge=document.createElement('span');badge.className='rank-number';badge.textContent=`${n}위`;b.append(img,badge);b.onclick=()=>lightbox(n-1);e.rankingGrid.append(b)})}
  function lightbox(i){if(!s.ranking.length)return;s.lightbox=(i+s.ranking.length)%s.ranking.length;const p=s.ranking[s.lightbox];e.lightboxImage.src=p.original;e.lightboxImage.alt=p.name;e.lightboxRank.textContent=`${s.lightbox+1}위`;e.lightboxName.textContent=p.name;e.downloadOriginal.href=p.original;e.downloadOriginal.download=p.name;e.lightbox.classList.add('open');document.body.style.overflow='hidden'}
  function closeLightbox(){e.lightbox.classList.remove('open');document.body.style.overflow=''}
  async function share(p,title='유나와 동재의 커플 셀피 월드컵'){if(!p)return;try{const data={title,text:title,files:[p.file]};if(navigator.share&&(!navigator.canShare||navigator.canShare(data)))await navigator.share(data);else if(navigator.share)await navigator.share({title,text:title});else toast('공유 메뉴를 지원하지 않습니다.')}catch(err){if(err?.name!=='AbortError')toast('공유하지 못했습니다.')}}
  const home=()=>{s.locked=false;screen('upload')};
  e.input.onchange=x=>addFiles(x.target.files);e.startButton.onclick=()=>start();e.clearButton.onclick=()=>clear();e.leftCandidate.onclick=()=>choose('left');e.rightCandidate.onclick=()=>choose('right');e.undoButton.onclick=undo;e.gameHomeButton.onclick=home;e.winnerHomeButton.onclick=home;e.shareWinnerButton.onclick=()=>share(s.champion,'우리의 1등 셀피 ♥');e.openWinnerButton.onclick=()=>lightbox(0);e.rankingButton.onclick=()=>screen('ranking');e.rankingBackButton.onclick=()=>screen('winner');e.rankingHomeButton.onclick=home;e.rematchButton.onclick=()=>start(s.pool);e.newSetLabel.onclick=()=>{s.replace=true};e.lightboxClose.onclick=closeLightbox;e.lightboxPrev.onclick=()=>lightbox(s.lightbox-1);e.lightboxNext.onclick=()=>lightbox(s.lightbox+1);e.lightboxShare.onclick=()=>share(s.ranking[s.lightbox]);e.lightbox.onclick=x=>{if(x.target===e.lightbox)closeLightbox()};
  let tx=0;e.lightbox.addEventListener('touchstart',x=>tx=x.touches[0]?.clientX||0,{passive:true});e.lightbox.addEventListener('touchend',x=>{const d=(x.changedTouches[0]?.clientX||0)-tx;if(Math.abs(d)>65)lightbox(s.lightbox+(d>0?-1:1))},{passive:true});document.addEventListener('keydown',x=>{if(!e.lightbox.classList.contains('open'))return;if(x.key==='Escape')closeLightbox();if(x.key==='ArrowLeft')lightbox(s.lightbox-1);if(x.key==='ArrowRight')lightbox(s.lightbox+1)});addEventListener('beforeunload',()=>s.photos.forEach(dispose));if('serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));renderSelected();
})();
